module.exports = {
  airlines: [
    { id: '4C', name: 'LATAM Colombia' },
    { id: '4M', name: 'LATAM Argentina' },
    { id: 'A3', name: 'Aegean Airlines' },
    { id: 'AA', name: 'American Airlines' },
    { id: 'AC', name: 'Air Canada' },
    { id: 'AF', name: 'Air France' },
    { id: 'AI', name: 'Air India' },
    { id: 'AM', name: 'Aeroméxico' },
    { id: 'AR', name: 'Aerolíneas Argentinas' },
    { id: 'AV', name: 'Avianca' },
    { id: 'AY', name: 'Finnair' },
    { id: 'AZ', name: 'Alitalia' },
    { id: 'BA', name: 'British Airways' },
    { id: 'BR', name: 'EVA Air' },
    { id: 'CA', name: 'Air China' },
    { id: 'CI', name: 'China Airlines' },
    { id: 'CM', name: 'Copa Airlines' },
    { id: 'CX', name: 'Cathay Pacific' },
    { id: 'CZ', name: 'China Southern' },
    { id: 'DL', name: 'Delta' },
    { id: 'ET', name: 'Ethiopian Airlines' },
    { id: 'EY', name: 'Etihad Airways' },
    { id: 'GA', name: 'Garuda Indonesia' },
    { id: 'IB', name: 'Iberia Airlines' },
    { id: 'JL', name: 'Japan Airlines' },
    { id: 'JP', name: 'Adria Airways' },
    { id: 'KE', name: 'Korean Air' },
    { id: 'KL', name: 'KLM' },
    { id: 'KQ', name: 'Kenya Airways' },
    { id: 'LA', name: 'LATAM Chile' },
    { id: 'LH', name: 'Lufthansa' },
    { id: 'LO', name: 'LOT Polish Airlines' },
    { id: 'LP', name: 'LATAM Perú' },
    { id: 'LX', name: 'SWISS' },
    { id: 'ME', name: 'MEA' },
    { id: 'MF', name: 'Xiamen Airlines' },
    { id: 'MH', name: 'Malaysia Airlines' },
    { id: 'MS', name: 'Egyptair' },
    { id: 'MU', name: 'China Eastern' },
    { id: 'NH', name: 'All Nippon Airways' },
    { id: 'NZ', name: 'Air New Zealand' },
    { id: 'OK', name: 'Czech Airlines' },
    { id: 'OS', name: 'Austrian Airlines' },
    { id: 'OU', name: 'Croatia Airlines' },
    { id: 'OZ', name: 'Asiana Airlines' },
    { id: 'PZ', name: 'LATAM Paraguay' },
    { id: 'QF', name: 'Qantas' },
    { id: 'QR', name: 'Qatar Airways' },
    { id: 'RJ', name: 'Royal Jordanian' },
    { id: 'RO', name: 'Tarom' },
    { id: 'S7', name: 'S7 Airlines' },
    { id: 'SA', name: 'South African Airways' },
    { id: 'SK', name: 'Scandinavian Airlines' },
    { id: 'SN', name: 'Brussels Airlines' },
    { id: 'SQ', name: 'Singapore Airlines' },
    { id: 'SU', name: 'Aeroflot' },
    { id: 'SV', name: 'Saudia' },
    { id: 'TG', name: 'Thai Airways' },
    { id: 'TK', name: 'Turkish Airlines' },
    { id: 'TP', name: 'TAP Portugal' },
    { id: 'UA', name: 'United Airlines' },
    { id: 'UL', name: 'SriLankan Airlines' },
    { id: 'UX', name: 'Air Europa' },
    { id: 'VN', name: 'Vietnam Airlines' },
    { id: 'VS', name: 'Virgin Atlantic' },
    { id: 'XL', name: 'LATAM Ecuador' },
    { id: 'ZH', name: 'Shenzhen Airlines' }
  ]
}
